Fix bugs in metrics collection and refactor.
brave/tokenizer pull request #35
Opened 2023-06-12 12:21 UTC by NullHypothesis

Please see the individual commit messages for more details.

2023-06-12 16:24 UTC, rillian requested changes

2023-06-12 16:26 UTC, rillian commented on forwarder_kafka.go
> +	if !k.isTimeToFlush() {
I think you have to manually inline `isTimeToFlush` so the two function bodies can share the same `RLock`.

2023-06-15 19:19 UTC, NullHypothesis commented on forwarder_kafka.go
> +	}
Fixed in 211f1c7.

2023-06-15 19:20 UTC, NullHypothesis commented on forwarder_kafka.go
> +	if !k.isTimeToFlush() {
Right, good catch. I moved the batch code to a separate struct in 5ccd4ad because a single mutex for all these variables is a bit messy.

2023-06-15 21:42 UTC, rillian commented on forwarder_kafka_batch.go
> +}
Just to check my understanding, this returns of a new copy of the `msgs` slice pointing to the same underlying array data as the `batch` struct member? If so that means the array data can be accessed without going through the RWMutex?

In this case that's probably fine. There are two implemented operations:  `addToken` appends new elements beyond the end of the returned slice, so the view will stay consistent; `reset` replaces the slice instead the batch struct with a new `nil` slice, which (I think?) allocates a new underlying array when `addToken` is called again. That would make both slices consistent over their lifetimes without locking.

2023-06-15 21:42 UTC, rillian commented on forwarder_kafka.go
> +	k.batch.conf = c.kafkaConfig
Should this also `k.batch.Lock()`? Maybe the outer lock effectively gates access to both?

2023-06-15 21:42 UTC, rillian commented on forwarder_kafka.go
> +	m.numForwarded.With(prometheus.Labels{outcome: success}).Add(float64(batchSize))
I think this can undercount, since someone might add more tokens between the `batchSize = k.batch.size()` call at the top of the function and `k.batch.messages()` which is passed to the writer. Better to use the length of the messages slice itself.

2023-06-15 21:42 UTC, rillian commented on forwarder_kafka.go
> +	k.batch.reset()
Since the `batch.messages()` call in `maybeFlush` and the `batch.reset()` call take separate locks, any tokens appended between the two will never be submitted.

2023-07-06 20:59 UTC, NullHypothesis commented
I revised the PR in 0b4b2a4 by using a lock-less token cache that uses channels instead.

2023-07-06 21:23 UTC, rillian approved these changes
I don't understand channels well, but seems reasonable. Let's give it a try!

2023-07-06 21:25 UTC, merged